pull_request_rules:
  - name: Automatic merge for dependabot PRs
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
      - base=master
    actions:
      merge:
        method: merge
  - name: Add depencies label when package.json is modified
    conditions:
      - files=package.json
    actions:
      label:
        add:
          - dependencies
  - name: Automatic merge on approval
    conditions:
      - base=master
      - '#approved-reviews-by>1'
    actions:
      merge:
        method: merge
